name: faps
channels:
  - defaults
dependencies:
  - pip
  - numpy==1.26
  - scipy
  - pandas
  - setuptools=52.0.0
  - python=3.9.2
  - tqdm
  - ipykernel
  - pip:
    - faps
    - -e 02_library/python
    - wquantiles
